import { useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { placeStore } from "../../../data/stores";
import "./PlaceForm.css";

const blank = { name: "", category: "", location: "", description: "", image: "", status: "Active" };
const PlaceForm = () => {
  const { id } = useParams(); const navigate = useNavigate();
  const editingPlace = id ? placeStore.get().find((place) => String(place.id) === String(id)) : null;
  const [form, setForm] = useState(() => editingPlace ? { ...editingPlace, category: editingPlace.category || editingPlace.type || "", image: editingPlace.image || editingPlace.images?.[0] || "", status: editingPlace.status || "Active" } : blank);
  const handleChange = ({ target: { name, value } }) => setForm((current) => ({ ...current, [name]: value }));
  const handleSubmit = (event) => { event.preventDefault(); if (!form.name.trim() || !form.category || !form.location.trim()) return alert("Place name, category, and location are required."); const place = { ...editingPlace, ...form, id: editingPlace?.id || `place-${Date.now()}`, name: form.name.trim(), location: form.location.trim(), description: form.description.trim(), type: form.category, images: form.image ? [form.image] : editingPlace?.images || [] }; const places = placeStore.get(); placeStore.save(editingPlace ? places.map((item) => String(item.id) === String(id) ? place : item) : [...places, place]); navigate("/admin/places"); };
  return <div className="place-form-page"><div className="place-form-header"><div><Link to="/admin/places" className="place-back">← Places</Link><h2>{editingPlace ? "Edit Place" : "Add Place"}</h2><p>{editingPlace ? "Update place information." : "Add a new tourist place to Tripwala."}</p></div><div className="place-form-actions"><Link to="/admin/places" className="place-cancel-btn">Cancel</Link><button type="submit" form="place-form" className="place-save-btn">{editingPlace ? "Update Place" : "Create Place"}</button></div></div><form id="place-form" className="place-form" onSubmit={handleSubmit}><div className="place-form-card"><div className="place-form-card-header"><h3>Basic Information</h3><span>Required information</span></div><div className="place-form-grid"><div className="place-field full"><label>Place Name <span>*</span></label><input name="name" value={form.name} onChange={handleChange} placeholder="Enter place name" required /></div><div className="place-field"><label>Category <span>*</span></label><select name="category" value={form.category} onChange={handleChange} required><option value="">Select category</option>{["Nature", "Waterfall", "Historical", "Adventure", "Beach", "Hidden Spot", "Food Spot", "Resort", "Home Stay", "Taxi"].map((category) => <option key={category} value={category}>{category}</option>)}</select></div><div className="place-field"><label>Location <span>*</span></label><input name="location" value={form.location} onChange={handleChange} placeholder="Example: Meppadi, Wayanad" required /></div><div className="place-field full"><label>Short Description</label><textarea name="description" value={form.description} onChange={handleChange} rows="5" placeholder="Write a short description..." /></div><div className="place-field full"><label>Cover Image</label><input name="image" value={form.image} onChange={handleChange} placeholder="/images/place.jpg" /><small>Enter an image URL or local image path.</small></div><div className="place-field"><label>Status</label><select name="status" value={form.status} onChange={handleChange}><option value="Active">Active</option><option value="Inactive">Inactive</option></select></div></div></div></form></div>;
};
export default PlaceForm;

