import { Link } from "react-router-dom";
import { useState } from "react";
import { getCategories, makeCategoryId, saveCategories } from "../../data/categoryStore";
import { getPlaces } from "../../data/placeStore";
import AdminLayout from "./AdminLayout";
import "./Admin.css";
const emptyForm = { label: "", id: "" };
const CategoryManagement = () => {
  const [categories, setCategories] = useState(getCategories); const [form, setForm] = useState(emptyForm); const [editingId, setEditingId] = useState(null); const [error, setError] = useState("");
  const persist = (next) => { setCategories(next); saveCategories(next); }; const reset = () => { setForm(emptyForm); setEditingId(null); setError(""); };
  const submit = (event) => { event.preventDefault(); const label = form.label.trim(); const id = (form.id.trim() || makeCategoryId(label)).toLowerCase(); if (!label) return setError("Enter a category name."); if (!/^[a-z0-9-]+$/.test(id)) return setError("URL ID may only use lowercase letters, numbers, and hyphens."); if (categories.some((item) => item.id === id && item.id !== editingId)) return setError("That URL ID already exists."); const category = { id, label }; persist(editingId ? categories.map((item) => item.id === editingId ? category : item) : [...categories, category]); reset(); };
  const countFor = (category) => getPlaces().filter((place) => place.categoryId === category.id || place.type === category.label).length;
  return <AdminLayout active="categories"><section className="admin-page"><div className="admin-page-heading"><p>Content management</p><h1>Category management</h1><span>Create categories, then open a category to manage its listings.</span></div><div className="category-management-grid"><section className="admin-panel"><h2>{editingId ? "Edit category" : "Add category"}</h2><form className="category-form" onSubmit={submit}><label>Category name<input value={form.label} onChange={(e) => setForm({ ...form, label: e.target.value })} required /></label><label>URL ID <small>Optional; generated from the name if blank.</small><input value={form.id} onChange={(e) => setForm({ ...form, id: e.target.value })} /></label>{error && <p className="admin-message error">{error}</p>}<div className="category-form-actions"><button className="admin-primary">{editingId ? "Save changes" : "Add category"}</button>{editingId && <button type="button" className="admin-secondary" onClick={reset}>Cancel</button>}</div></form></section><section className="admin-panel"><div className="panel-title"><h2>Category lists</h2><span>{categories.length} total</span></div><div className="category-list">{categories.map((item) => <article key={item.id}><div><strong>{item.label}</strong><code>{countFor(item)} listings · {item.id}</code></div><div className="category-row-actions"><Link className="admin-row-link" to={`/admin/places?category=${item.id}`}>Manage</Link><button onClick={() => { setEditingId(item.id); setForm(item); }}>Edit</button><button className="danger" onClick={() => { if (window.confirm(`Delete “${item.label}”?`)) persist(categories.filter((category) => category.id !== item.id)); }}>Delete</button></div></article>)}</div></section></div></section></AdminLayout>;
};
export default CategoryManagement;
